DATASET:
  NAME: "DescribableTextures"
TRAINER:
  MoELASP:
    GROUPS: [1, 1, 1, 4, 2]
    LASP_PROMPTS: [
        "{} texture.",
    ## General photo prompts
        "a photo of a {}.",
        # "a photo of the {}.",
        "a photo of many {}.",
    ## Low resolution and pixelated photos
        "a low resolution photo of the {}.",
        "a low resolution photo of a {}.",
        "a pixelated photo of the {}.",
        "a pixelated photo of a {}.",
    ## Good quality photos
        "a good photo of the {}.",
        "a good photo of a {}.",
    ]
    # GROUPS: [1, 1, 1]
    # LASP_PROMPTS: [
    #   "A photo of a {} that your hands would ache to hold, as if the tactile sensation of its texture would seep into your pores, lingering long after you’ve let it go.",
    #   "A photo of a {} that your eyes trace with reverence, as if mapping the intricate land- scape of its texture, and your fingertips hum with anticipation to explore its tactile secrets.",
    #   "A photo of a {} that unfolds like a sensory tapestry, weaving together tactile whispers, visual nuances, and the promise of discovery."
    # ]
