DATASET:
  NAME: "EuroSAT"
TRAINER:
  MoELASP:
    # GROUPS: [1, 1, 1]
    # LASP_PROMPTS: [
    #   "A Sentinel-2 satellite image capturing the symphony of human and environmental harmonies in European {}, as technology's gaze harmonizes with nature’s rhythm.",
    #   "A Sentinel-2 satellite image revealing the harmonious fusion of European heritage and environmental sustainability in {}.",
    #   "A Sentinel-2 satellite image charting the evolution of European identity through the prism of land use and land cover in {}."
    # ]
    GROUPS: [1, 1, 2, 2,  4, 2]
    LASP_PROMPTS: [
    # ## Photos of aircraft
        # "a photo of a {}, a type of aircraft.",
        "a centered satellite photo of {}.",
    ## General photo prompts
        "a photo of a {}.",
        # "a photo of the {}.",
        "a photo of the large {}.",
        "a photo of a large {}.",
        #
        "a photo of the small {}.",
        "a photo of a small {}.",
    ## Low resolution and pixelated photos
        "a low resolution photo of the {}.",
        "a low resolution photo of a {}.",
        "a pixelated photo of the {}.",
        "a pixelated photo of a {}.",
    ## Good quality photos
        "a good photo of the {}.",
        "a good photo of a {}.",
    ]
    

