DATASET:
  NAME: "OxfordPets"
TRAINER:
  MoELASP:
    # GROUPS: [1, 1, 1]
    # LASP_PROMPTS: [
    # "A cherished and loyal {} with a warm and loving demeanor, often found in the hearts of its owners as a constant companion, bringing immense joy and comfort to their daily lives with its playful antics and snuggles.",
    # "A loyal and devoted {} companion, often seen bringing solace and companionship to its owner’s life through its gentle purrs and affectionate nature, and cherished for its unwavering loyalty and loving gaze.",
    # "A majestic {} with a gentle purr, often seen lounging in the sunbeams that stream through the windows, bringing joy and comfort to its owner’s life with its soft fur and loving companionship."
    # ]

    GROUPS: [1, 2, 1, 1, 4, 2]
    LASP_PROMPTS: [
        "a photo of the small {}.",
        #
        "a photo of the large {}.",
        "a photo of a large {}.",
    ## General photo prompts
        "a photo of a {}.",
        # "a photo of the {}.",
        "a photo of many {}.",
    ## Low resolution and pixelated photos
        "a low resolution photo of the {}.",
        "a low resolution photo of a {}.",
        "a pixelated photo of the {}.",
        "a pixelated photo of a {}.",
    ## Good quality photos
        "a good photo of the {}.",
        "a good photo of a {}.",
    ]
