DATASET:
  NAME: "StanfordCars"
TRAINER:
  MoELASP:
    # GROUPS: [1, 1, 1]
    # LASP_PROMPTS: [
    #   "A photo of a {} parked in a modern garage, with a minimalist interior design and subtle hints of high-tech features, emphasizing its sleek design and advanced engineering.",
    #   "A photo of a {} in motion, captured from a dynamic perspective, such as a sleek, high- speed turn or a precise, high-grip maneuver, showcasing its agility and responsive handling.",
    #   "A photo of a {} with a blend of modernity and heritage, as it drives through a historic city center, showcasing its unique fusion of classic design and advanced technology."
    # ]

    GROUPS: [3, 1, 1, 4, 2]
    LASP_PROMPTS: [
        "A photo of the high-performance {}.",
        "A photo of the modern {}.",
        "A photo of the fast {}.",
    ## General photo prompts
        "a photo of a {}.",
        # "a photo of the {}.",
        "a photo of many {}.",
    ## Low resolution and pixelated photos
        "a low resolution photo of the {}.",
        "a low resolution photo of a {}.",
        "a pixelated photo of the {}.",
        "a pixelated photo of a {}.",
    ## Good quality photos
        "a good photo of the {}.",
        "a good photo of a {}.",
    ]

  