DATASET:
  NAME: "SUN397"
TRAINER:
  MoELASP:
    # GROUPS: [1, 1, 1]
    # LASP_PROMPTS: [
    #   "A peaceful haven of a {}, where natural serenity meets subtle human touch.",
    #   "A picturesque snapshot of a {}, where human presence subtly shapes the serene am- biance.",
    #   "A captivating image of a {}, where vibrant colors and textures evoke a sense ofwonder and curiosity."
    # ]
    GROUPS: [1, 1, 4, 2]
    LASP_PROMPTS: [
    ## General photo prompts
        "a photo of a {}.",
        # "a photo of the {}.",
        "a photo of many {}.",
    ## Low resolution and pixelated photos
        "a low resolution photo of the {}.",
        "a low resolution photo of a {}.",
        "a pixelated photo of the {}.",
        "a pixelated photo of a {}.",
    ## Good quality photos
        "a good photo of the {}.",
        "a good photo of a {}.",
    ]

