DATASET:
  NAME: "UCF101"
TRAINER:
  MoELASP:
    # GROUPS: [1, 1, 1]
    # LASP_PROMPTS: [
    # "The video captures a person skillfully executing a {} action that requires a high level of physical dexterity and coordination in the context of sports.",
    # "The {} action is a nuanced demonstration of human physical skill, requiring coordi- nation and precise movements.",
    # "The video captures a person engaged in a meticulous and precise manner while per- forming the {} action, showcasing exceptional control and technique."
    # ]
    GROUPS: [1, 1, 1, 1, 4, 2]
    LASP_PROMPTS: [
        "a photo of a person doing {}.",
        #
        "a {} in a video game.",
    ## General photo prompts
        "a photo of a {}.",
        # "a photo of the {}.",
        "a photo of many {}.",
    ## Low resolution and pixelated photos
        "a low resolution photo of the {}.",
        "a low resolution photo of a {}.",
        "a pixelated photo of the {}.",
        "a pixelated photo of a {}.",
    ## Good quality photos
        "a good photo of the {}.",
        "a good photo of a {}.",
    ]
