DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 32
  TEST:
    BATCH_SIZE: 32
  NUM_WORKERS: 8

INPUT:
  SIZE: (224, 224)
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.48145466, 0.4578275, 0.40821073]
  PIXEL_STD: [0.26862954, 0.26130258, 0.27577711]
  TRANSFORMS: ["random_resized_crop", "random_flip", "normalize"]

OPTIM:
  NAME: "sgd"
  LR: 0.032 # 0.002
  MAX_EPOCH: 50
  LR_SCHEDULER: "cosine"
  WARMUP_EPOCH: 5
  WARMUP_TYPE: "constant"
  WARMUP_CONS_LR: 1e-5
  #WEIGHT_DECAY: 0.01

TRAIN:
  PRINT_FREQ: 20

MODEL:
  BACKBONE:
    NAME: "ViT-B/16"

TRAINER:
  MoELASP:
    # ENABLE: True
    # ENABLE_CORRECTION: True
    FINETUNE_VIT_LN: True
    ENABLE: True
    ENABLE_CORRECTION: True
    # FINETUNE_VIT_LN: False
    N_CTX: 4
    # CTX_INIT: ['A photo of a', "An image of a", 'A drawing of a', 'A painting of a']
    # CTX_INIT: ["A photo of a", "An image of a",  "A painting of a", "A photo of a big", "A photo of a small", "A photo of many"]
    CTX_INIT: ['A photo of a']
   
    PREC: "amp"
    LASP_LOSS_WEIGHT: 1.
    GATE_LOSS_WEIGHT: 1.
