DATASET:
  NAME: "Food101"
DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 32
OPTIM:
  NAME: "sgd"
  LR: 0.032 # 0.002
TRAINER:
  MoCoOp:
    GROUPS: [1, 3, 4, 2]
    LASP_PROMPTS: [
    ## General photo prompts
        "a photo of a  {}.",
        # "a photo of the {}.",
        "a photo of the delicious {}.",
        "a photo of the tasty {}.",
        "A dish of the {}.",
    ## Low resolution and pixelated photos
        "a low resolution photo of the {}.",
        "a low resolution photo of a {}.",
        "a pixelated photo of the {}.",
        "a pixelated photo of a {}.",
    ## Good quality photos
        "a good photo of the {}.",
        "a good photo of a {}.",
    ]
   

