DATASET:
  NAME: "OxfordFlowers"
TRAINER:
  MoCoOp:
    GROUPS: [1, 1, 1, 4, 2]
    PROMPTS: [
    ## Photos of flowers
    #  "a photo of a {}, a type of flower.",
    # ## Photos of aircraft
      "a photo of a {}, a type of flower.",
    ## "Itap" (I took a picture) photos
        # "itap of a {}.",
        # "itap of the {}.",
    ## Art and renditions
        # "art of the {}.",
        # "a rendering of a {}.",
        # "a rendering of the {}.",
        # "a rendition of the {}.",
    ## General photo prompts
        "a photo of a {}.",
        # "a photo of the {}.",
        "a photo of many {}.",
    ## Low resolution and pixelated photos
        "a low resolution photo of the {}.",
        "a low resolution photo of a {}.",
        "a pixelated photo of the {}.",
        "a pixelated photo of a {}.",
    ## Good quality photos
        "a good photo of the {}.",
        "a good photo of a {}.",
    # ## Origami photos
        # "a origami {}.",
    # ## Texture photos
        # "{} texture.",
    ]
  

