DATASET:
  NAME: "StanfordCars"
TRAINER:
  MoCoOp:
    GROUPS: [3, 1, 1, 4, 2]
    LASP_PROMPTS: [
        "A photo of the high-performance {}.",
        "A photo of the modern {}.",
        "A photo of the fast {}.",
    ## General photo prompts
        "a photo of a {}.",
        # "a photo of the {}.",
        "a photo of many {}.",
    ## Low resolution and pixelated photos
        "a low resolution photo of the {}.",
        "a low resolution photo of a {}.",
        "a pixelated photo of the {}.",
        "a pixelated photo of a {}.",
    ## Good quality photos
        "a good photo of the {}.",
        "a good photo of a {}.",
    ]

  