DATASET:
  NAME: "UCF101"
TRAINER:
  MoCoOp:
    GROUPS: [1, 1, 1, 1, 4, 2]
    PROMPTS: [
        "a photo of a person doing {}.",
        "a {} in a video game.",
    ## General photo prompts
        "a photo of a {}.",
        # "a photo of the {}.",
        "a photo of many {}.",
    ## Low resolution and pixelated photos
        "a low resolution photo of the {}.",
        "a low resolution photo of a {}.",
        "a pixelated photo of the {}.",
        "a pixelated photo of a {}.",
    ## Good quality photos
        "a good photo of the {}.",
        "a good photo of a {}.",
    ]
